# Generated by Django 3.2.9 on 2021-12-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfacility',
            options={'verbose_name_plural': 'client facilities'},
        ),
    ]
