# Generated by Django 3.2.9 on 2021-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
