# Generated by Django 3.2.9 on 2021-12-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
    ]
