# Generated by Django 3.2.9 on 2021-12-02 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('client_facility', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_images', models.ManyToManyField(blank=True, to='image.Image')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('menu_items', models.ManyToManyField(blank=True, to='menu.MenuItem')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('description', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_facility.clientfacility')),
                ('menu_categories', models.ManyToManyField(to='menu.MenuCategory')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
