# Generated by Django 3.2.9 on 2021-12-02 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waiter', '0001_initial'),
        ('menu', '0001_initial'),
        ('table', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('amount', models.IntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitem')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('date', models.DateTimeField(auto_created=True)),
                ('order_items', models.ManyToManyField(to='order.OrderItem')),
                ('table_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='table.table')),
                ('waiter_assigned', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='waiter.waiter')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
