# Generated by Django 3.2.9 on 2021-12-07 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('waiter', '0001_initial'),
        ('menu', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In progress'), ('PREPARED', 'Prepared'), ('SERVED', 'Served'), ('PAID', 'Paid')], default='RECEIVED', max_length=15)),
                ('table_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='table.table')),
                ('waiter_assigned', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waiter.waiter')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('softdeletablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.softdeletablemodel')),
                ('amount', models.IntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
            bases=('shared.softdeletablemodel',),
            managers=[
                ('non_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
