# Generated by Django 3.2.9 on 2021-12-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In progress'), ('PREPARED', 'Prepared'), ('SERVED', 'Served'), ('PAID', 'Paid')], default='RECEIVED', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter_assigned',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waiter.waiter'),
        ),
    ]
